apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdiekNDQkZlZ0F3SUJBZ0lSQUx3YVdwclhub2tSc3BBUmkxQ2hVb2N3RFFZSktvWklodmNOQVFFTUJRQXcKU3pFTE1Ba0dBMVVFQmhNQ1FWUXhFREFPQmdOVkJBb1RCMXBsY205VFUwd3hLakFvQmdOVkJBTVRJVnBsY205VApVMHdnVWxOQklFUnZiV0ZwYmlCVFpXTjFjbVVnVTJsMFpTQkRRVEFlRncweU16QTJNRGd3TURBd01EQmFGdzB5Ck16QTVNRFl5TXpVNU5UbGFNQnN4R1RBWEJnTlZCQU1NRUNvdWJHbG5kV0Z1WjJoMWFTNXdjbTh3Z2dFaU1BMEcKQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURRdEoxalB6VjhpdHFwUlNJQXlVbVpZTTA0T2lNOAplM2JVWjh2Sk1SLytpV0NZRHpVaE9GenpuWURHdE9jRHFsY1dMQVAwMmd0NndxU0R4MlUxRFovRjJoR3lDd2lECnUwcWZGd3FSaU1CVThBMHNmaHpzZEFEZFMyMEJidFZ1RmRNZ2YwSEgzVXlnTCs5MEtLRTQ3YzBWdEpQQWUzcmsKMFpWMG5XNklsUk5mTXE3MmF4MXExelVESERVa3Q0MlFBdGIybmtXNjk4ZndibTFQcEF3YTJzckRzT0EvK2d0YQoxaU8wbWRWSmgwSytLZ2VWV3Y0NXhpNUlmaGdjZmFuK2lBSDRKQWtXeGhsWDVTT1lBZStvUW1zTHFJdXFJMkh1CmNhYjN0V2xheTgrMjJVTlZ1cWU2NHpwQ21UZ0YrUDFaZVJFVXJhY3VsQitzWUlrQ0swREZoT041QWdNQkFBR2oKZ2dKOE1JSUNlREFmQmdOVkhTTUVHREFXZ0JUSTJYaG9vdGtaYU5VOWN0NWZDajdjdFlhR3BqQWRCZ05WSFE0RQpGZ1FVYW8ySXorZzhYUzQzVWM3cFM3MkduKzZSRHVvd0RnWURWUjBQQVFIL0JBUURBZ1dnTUF3R0ExVWRFd0VCCi93UUNNQUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Fa0dBMVVkSUFSQ01FQXcKTkFZTEt3WUJCQUd5TVFFQ0FrNHdKVEFqQmdnckJnRUZCUWNDQVJZWGFIUjBjSE02THk5elpXTjBhV2R2TG1OdgpiUzlEVUZNd0NBWUdaNEVNQVFJQk1JR0lCZ2dyQmdFRkJRY0JBUVI4TUhvd1N3WUlLd1lCQlFVSE1BS0dQMmgwCmRIQTZMeTk2WlhKdmMzTnNMbU55ZEM1elpXTjBhV2R2TG1OdmJTOWFaWEp2VTFOTVVsTkJSRzl0WVdsdVUyVmoKZFhKbFUybDBaVU5CTG1OeWREQXJCZ2dyQmdFRkJRY3dBWVlmYUhSMGNEb3ZMM3BsY205emMyd3ViMk56Y0M1egpaV04wYVdkdkxtTnZiVENDQVFRR0Npc0dBUVFCMW5rQ0JBSUVnZlVFZ2ZJQThBQjJBSzMzdnZwOC94RElpNTA5Cm5CNCtHR3EwWnlsZHo3RU1KTXFGaGpUcjNJS0tBQUFCaUp2ZUpaa0FBQVFEQUVjd1JRSWdWcGk2WFFNVnVEcGwKVmdMY2EzWk51ZnlYdDVxdy9wWFV3OG1iRTZUTXNKSUNJUURNVzZpSi91VGJVU094UEcrUXBlbTJGUFVYLzl3Swoya2RqT0NIK2J3dXJCZ0IyQUhveWpGVFl0eTIySU9vNDRGSWU2WVFXY0RJVGhVMDcwaXZCT2xlalV1dFNBQUFCCmlKdmVKZ2tBQUFRREFFY3dSUUlnUUx2YmJSRTFPRkVoNHJTUHMyUUhyd211KzVLcEdUaTd4bC8yTmVSMnlTQUMKSVFDRVNTZytpM1ArVjFBclEwSkE3NEdTNi9NR2VZWlRyRHpkZ0gwaU9nM0VkekFiQmdOVkhSRUVGREFTZ2hBcQpMbXhwWjNWaGJtZG9kV2t1Y0hKdk1BMEdDU3FHU0liM0RRRUJEQVVBQTRJQ0FRQnQrQmtnWDhETTVKcGFVbGZPClNrbFl1cFZRT2Rib3dwTG5FL0xGc1ltWnliV0dEbnN5Ym5acXUyVTZZMERhVlpKaEhrazBvQW9rNmZ5Y2wvMU8KeklOQWU3MWpRbUdBUGlCVWZRbjh1MGFmekRwRlo5NjBWTDZYSlNVbkdaQnMwRHpaay9LeDZ3RG96OWxtWkRqeQpXbEFqSm9UWjE3OFlSTHFjZC8yd3pLZXZBK254SktuaHV5cldCWWVoRGxEK215MnozNW5BMlN6V25HampXT2s4CmtwaEI0YStWRHlMSjd2NGNJTHZiUkRwZTZvWUhvaFFzNnpQaWd5d1cvUGZkMUVaL0IzUitYREc1ak96bEJQWU8KbnhwT0orb1ZJbXRpQUh6OUFOSTMxeXNNZWFmcTFKbnBDbUZkc0U3dWw4V1dmK1dJWnVKalJHdXFmSmFiSTVxQwp3REo5QU84NEI0ZnI5YVVPMTl2UlFmbVRHdnNMRDY4OFppRm5BWnpSWllWaVNFSFZlZjBJbXNiYUtiWU5OZmtlCk83cG9IZDBxWjh3WE1RbTN0WkN3SG85eFRTcVhLVHlHV0tTYWdrRnMzODg0NHVNQ29kdHRjTTVFRTFvb2ZIY1UKY2NZUzQ3Y1VxZC9UODlraHVpMERESUpGeHdFS3JRVzJOdEM3d2FWMkhETFF6UUttazVvRGRjc1pFdDFGbHVKUwpGYnZ5QnRCTjRCckY0RWxPelJXd1VVd2xnenRDczdzZitUOGNPNzdNN0p2aHlVM0lhQWVxTG5XUGhUUC94TjdZClcvbUNzOUx2WDloZTgrUHZTMHQ1c204d1ZKNkJTOXlETkFWU2VXbWtuQXVkQ1ZGYjZFaGtCYzR3ZzM0SG5EVnYKTHhhZkdTemZGa21EMC9NcnNTdDZ2QmsxblE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlHMVRDQ0JMMmdBd0lCQWdJUWJGV3IyOUFIa3NlZEJ3ellFWjdXdnpBTkJna3Foa2lHOXcwQkFRd0ZBRENCCmlERUxNQWtHQTFVRUJoTUNWVk14RXpBUkJnTlZCQWdUQ2s1bGR5QktaWEp6WlhreEZEQVNCZ05WQkFjVEMwcGwKY25ObGVTQkRhWFI1TVI0d0hBWURWUVFLRXhWVWFHVWdWVk5GVWxSU1ZWTlVJRTVsZEhkdmNtc3hMakFzQmdOVgpCQU1USlZWVFJWSlVjblZ6ZENCU1UwRWdRMlZ5ZEdsbWFXTmhkR2x2YmlCQmRYUm9iM0pwZEhrd0hoY05NakF3Ck1UTXdNREF3TURBd1doY05NekF3TVRJNU1qTTFPVFU1V2pCTE1Rc3dDUVlEVlFRR0V3SkJWREVRTUE0R0ExVUUKQ2hNSFdtVnliMU5UVERFcU1DZ0dBMVVFQXhNaFdtVnliMU5UVENCU1UwRWdSRzl0WVdsdUlGTmxZM1Z5WlNCVAphWFJsSUVOQk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBaG1semZxTzFNZGdqCjRXM2RwQlBUVkJYMUF1dmNBeUcxZmwwZFVudy9NZXVlQ1d6UldUaGVaMzVMVm85MWtMSTNERFZhWktXK1RCQXMKSkJqRWJZbU13Y1dTVFdZQ2c1MzM0U0YwK2N0REFzRnhzWCtyVERoOWtTckcvNG1wNk9TaHViTGFFSVVKaVpvNAp0ODczVHVTZDBXajVEV3QzRHRwQUc4VDM1bC92K3hyTjh1YjhQU1NvWDVWa2d3K2pXZjRLUXROdlVGTERxOG1GCldoVW5QTDZqSEFBRFhwdnM0bFROWXdPdHg5eVF0YnB4d1N0N1FKWTErSUNybVJKQjZCdUtSdC9qZkRKRjlKc2MKUlFWbEhJeFFkS0FKbDdvYVZuWGdEa3F0azJxZGRkM2tDRFhkNzRndjgxM0c5MXo3Q2pzR3lKOTNvSklsTlMzVQpnRmJENlY1NEpNZ1ozclNtb3RZYno5OG9aeFg3TUtidENtMWFKL3EraFR2MllLMXlNeHJuZmNpZUttT1lCYkZECmhuVzVPNlJNQTcwM2RCSzkyajZYUk4yRXR0TGtRdXVqWmd5K2pYUkt0YVdNSWxrTmtXSm1PaUhtRXJRbmdIdnQKaU5rSWNqSnVtcTFkZEZYNGlhVEk0MGE2emd2SUJ0eEZlRHMyUmZjYUg3M2VyN2N0TlVVcWdRVDVyRmdKaE1tRgp4NzZyUWdCNU9aVWtvZGI1azJleDdQK0d1NEo4NmJTMTUwOTRVdVljVjA5aFZla25tVGg1RXg5Q0JLaXBMUzJXCjJ3S0Jha2YrYVZZbk5DVTZTMG5BU3F0MnhyWnBHQzF2N3Y2RGh1ZXB5eUp0bjNxU1YyUG9CaVU1U3FsK2FBUnAKd1VpYlFNR200NGdqeU5EcURsVnArU2hMUWxVSDl4OENBd0VBQWFPQ0FYVXdnZ0Z4TUI4R0ExVWRJd1FZTUJhQQpGRk41djFxcUswclBWSURoMkp2QW5mS3lBMmJMTUIwR0ExVWREZ1FXQkJUSTJYaG9vdGtaYU5VOWN0NWZDajdjCnRZYUdwakFPQmdOVkhROEJBZjhFQkFNQ0FZWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFkQmdOVkhTVUUKRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdJZ1lEVlIwZ0JCc3dHVEFOQmdzckJnRUVBYkl4QVFJQwpUakFJQmdabmdRd0JBZ0V3VUFZRFZSMGZCRWt3UnpCRm9FT2dRWVkvYUhSMGNEb3ZMMk55YkM1MWMyVnlkSEoxCmMzUXVZMjl0TDFWVFJWSlVjblZ6ZEZKVFFVTmxjblJwWm1sallYUnBiMjVCZFhSb2IzSnBkSGt1WTNKc01IWUcKQ0NzR0FRVUZCd0VCQkdvd2FEQS9CZ2dyQmdFRkJRY3dBb1l6YUhSMGNEb3ZMMk55ZEM1MWMyVnlkSEoxYzNRdQpZMjl0TDFWVFJWSlVjblZ6ZEZKVFFVRmtaRlJ5ZFhOMFEwRXVZM0owTUNVR0NDc0dBUVVGQnpBQmhobG9kSFJ3Ck9pOHZiMk56Y0M1MWMyVnlkSEoxYzNRdVkyOXRNQTBHQ1NxR1NJYjNEUUVCREFVQUE0SUNBUUFWRHdvSXpRRFYKZXJjVDBlWXFaakJOSjhWTld3VkZsUU90WkVScW41aVduRVZhTFpaZHp4bGJ2ejJGeDBFeFVOdVVFZ1lrSVZNNApZb2NLa0NRN2hPNW5vaWNvcS9EckVZSDVJdU5jdVcxSThKSlo5REx1QjFmWXZJSGxaMkpHNDZpTmJWS0EzeWdBCkV6ODZSdkRRbHQyQzQ5NHFxUFZJdFJqcno5WWxKRUdUMERydHR5QXBxMFlMRkR6ZitaMXBrTWhoN2MrN2ZYZUoKcW1JaGZKcGR1S2M4SEVRa1lRUVNoZW40MjZTM0gwSnJJQWJLY0JDaXlZRnVPaGZ5dnV3VkNGRGZGdnJqQURqZAo0algxdVFYZDE2MUl5RlJibTg5czJPajVvVTF3RFl6NXN4K2hvQ3VoNmxTcysvdVB1V29tSXEzeTFHREZOYWZXCitMc0hCVTE2bFFvNVEyeWgyNWxhUXNLUmd5UG1NcEhKOThlZG02eTJzSFVhYkFTbVJIeHZHaXV3d0UyNWFEVTAKMlNBZWVweUltSjJDekI4MFlHN1d4bHluSHFOaHBFN3hmQzdQelFsTGdtZkVIZFUrdEhGZVFhelJRbnJGa1cyVwprcVJHSXE3Y0tSbnl5cHZqUE1ramVpVjlsUmRBTTlmU0p2c0Izc3ZVdXUxY29JRzF4eEkxeWVnb0dNNHI1UVA0ClJHSVZ2WWFpSTc2QzBkam9TYlEvZGtJVVVYUXVCOEFMNWp5SDM0ZzNCWmFhWHl2cG1uVjRpbHBwTVhWQW5BWUcKT041MVdoSjZXMHhOZE5Kd3pZQVNaWUgrdG1DV0krTjYwR3YyTk5NR0h3TVo3ZTliWGd6VUNaSDVGYUJGREdSNQpTOVZXcUhCNzNRK095SVZ2SWJLWWNTYzJ3L2FTdUZLR1NBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRmdUQ0NCR21nQXdJQkFnSVFPWEpFT3ZraXQxSFgwMndRM1RFMWxUQU5CZ2txaGtpRzl3MEJBUXdGQURCNwpNUXN3Q1FZRFZRUUdFd0pIUWpFYk1Ca0dBMVVFQ0F3U1IzSmxZWFJsY2lCTllXNWphR1Z6ZEdWeU1SQXdEZ1lEClZRUUhEQWRUWVd4bWIzSmtNUm93R0FZRFZRUUtEQkZEYjIxdlpHOGdRMEVnVEdsdGFYUmxaREVoTUI4R0ExVUUKQXd3WVFVRkJJRU5sY25ScFptbGpZWFJsSUZObGNuWnBZMlZ6TUI0WERURTVNRE14TWpBd01EQXdNRm9YRFRJNApNVEl6TVRJek5UazFPVm93Z1lneEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUlFd3BPWlhjZ1NtVnljMlY1Ck1SUXdFZ1lEVlFRSEV3dEtaWEp6WlhrZ1EybDBlVEVlTUJ3R0ExVUVDaE1WVkdobElGVlRSVkpVVWxWVFZDQk8KWlhSM2IzSnJNUzR3TEFZRFZRUURFeVZWVTBWU1ZISjFjM1FnVWxOQklFTmxjblJwWm1sallYUnBiMjRnUVhWMAphRzl5YVhSNU1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBZ0JKbEZ6WU93OXNJCnM5Q3NWdzEyN2MwbjAweXRVSU5oNHFvZ1RRa3RaQW5jem9tZnpEMnA3UGJQd2R6eDA3SFdlemNvRVN0SDJqbkcKdkRvWnRGK212WDJkbzJOQ3RuYnlxVHNya2ZqaWI5RHNGaUNRQ1Q3aTZIVEpHTFNSMUdKazIzK2pCdkdJR0dxUQpJank4L2hQd2h4Ujc5dVFmanRUa1VjWVJaMFlJVWN1R0ZGUS92RFArZm15Yy94YWRHTDFSampXbXAyYkljbWZiCklXYXgxSnQ0QThCUU91ak04Tnk4bmt6K3J3V1dOUjlYV3JmL3p2azl0eXkyOWxUZHlPY1NPazJ1VElxM1hKcTAKdHlBOXluOGlOSzUrTzJobUFVVG5BVTVHVTVzellQZVV2bE0za0hORDh6TERVKy9icXY1MFRtbkhhNHhnazk3RQp4d3pmNFRLdXpKTTdVWGlWWjR2dVBWYitETkJwRHhzUDh5VW1hek50OTI1SCtuTkQ1WDRPcFdheEtYd3loR05WCmljUU53Wk5VTUJrVHJOTjlONmZyWFRwc05WemJRZGNTMnFsSkM5L1lnSW9KazJLT3RXYlBKWWpOaExpeFA2UTUKRDlrQ251c1NUSlY4ODJzRnFWNFdnOHk0WitMb0U1M01XNExUVExQdFcvL2U1WE9zSXpzdEFMODFWWFFKU2RoSgpXQnAva2pibVVaSU84eVo5SEUwWHZNbnNReWJRdjBGZlFLbEVSUFNaNTFlSG5sQWZWMVNvUHYxMFl5K3hVR1VKCjVsaENMa01hVExUd0pVZForZ1FlazlRbVJrcFFnYkxldm5pMy9HY1Y0Y2xYaEI0UFk5YnBZcnJXWDFVdTZsekcKS0FnRUpUbTREaXVwOGt5WEhBYy9EVkwxN2U4dmdnOENBd0VBQWFPQjhqQ0I3ekFmQmdOVkhTTUVHREFXZ0JTZwpFUW9qUHBieEIremlyeW52Z3FWLzBEQ2t0REFkQmdOVkhRNEVGZ1FVVTNtL1dxb3JTczlVZ09IWW04Q2Q4cklEClpzc3dEZ1lEVlIwUEFRSC9CQVFEQWdHR01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0VRWURWUjBnQkFvd0NEQUcKQmdSVkhTQUFNRU1HQTFVZEh3UThNRG93T0tBMm9EU0dNbWgwZEhBNkx5OWpjbXd1WTI5dGIyUnZZMkV1WTI5dApMMEZCUVVObGNuUnBabWxqWVhSbFUyVnlkbWxqWlhNdVkzSnNNRFFHQ0NzR0FRVUZCd0VCQkNnd0pqQWtCZ2dyCkJnRUZCUWN3QVlZWWFIUjBjRG92TDI5amMzQXVZMjl0YjJSdlkyRXVZMjl0TUEwR0NTcUdTSWIzRFFFQkRBVUEKQTRJQkFRQVloMUhjZENFOW5JcmdKN2N6MEM3TTdQRG15MTRSM2lKdm0zV09ubkwrNU5iK3FoK2NsaTN2QTBwKwpydlNOYjNJOFF6dkFQK3U0MzF5cXFjYXU4dnpZN3FON1EvYUdObndVNE0zMDl6LyszcmkwaXZDUmx2NzlRMlIrCi9jelNBYUY5ZmZnWkdjbENLeE8vV0l1NnBLSm1CSGFJa1U0TWlSVE9vazNKTXJPNjZCUWF2SEh4Vy9CQkM1Z0EKQ2lJREVPVU1zZm5Oa2pjWjdUdng1RHEyK1VVVEpuV3Z1NnJ2UDN0M085TEVBcEU5R1FEVEYxdzUyejk3R0ExRgp6Wk9GbGk5ZDMxa1dUejlSdmRWRkdEL3RTbzdvQm1GMEl4YTFEVkJ6SjBSSGZ4QmRpU3ByaFRFVXhPaXBha3lBCnZHcDR6N2gvam5aeW1ReWQvdGVSQ0JhaG8xK1YKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBMExTZFl6ODFmSXJhcVVVaUFNbEptV0ROT0RvalBIdDIxR2ZMeVRFZi9vbGdtQTgxCklUaGM4NTJBeHJUbkE2cFhGaXdEOU5vTGVzS2tnOGRsTlEyZnhkb1JzZ3NJZzd0S254Y0trWWpBVlBBTkxINGMKN0hRQTNVdHRBVzdWYmhYVElIOUJ4OTFNb0MvdmRDaWhPTzNORmJTVHdIdDY1TkdWZEoxdWlKVVRYekt1OW1zZAphdGMxQXh3MUpMZU5rQUxXOXA1RnV2Zkg4RzV0VDZRTUd0ckt3N0RnUC9vTFd0WWp0Sm5WU1lkQ3Zpb0hsVnIrCk9jWXVTSDRZSEgycC9vZ0IrQ1FKRnNZWlYrVWptQUh2cUVKckM2aUxxaU5oN25HbTk3VnBXc3ZQdHRsRFZicW4KdXVNNlFwazRCZmo5V1hrUkZLMm5McFFmckdDSkFpdEF4WVRqZVFJREFRQUJBb0lCQUJQOHJCTHdYM3F2SUl3ego0UE1DMDkvU3I2eWFFcnhNMVo4M1ZvS015QlBjQzZwY1VIbi9PQldqaUl6ZkQ3MmYzMG15Q3VuMHhNTXJwMDR3CmR3Nks0TGwxcmhxbktGaFhSQ2p5cjdJcXpzS0RuN3RhVTRKSWhMbXNxc0tIbnZ4MUxod3ZXN2tjaGlWVUdlSTkKcnR6eEZ5SWtRajhkaERJc0tSdzdKSFlEa3RDYnNXQjVDc3d5R0Y3cGEvdGZOZExZWG5oS25UaFg0YXJOY3paSwpSVERYWEFWT3pEeHhZV0dLeS9HYWZFc0lUZU82R1RISGhFemRVNGtJZUFreWFKOXhKOVNtaWM5Y1pMQ05SUHJpCis0SVNpeGFudHVHMi90WmZxU0xEV3NpUG9rZTF2R1RkVGZTUEY0UWE3QjFibFR5ZXZkZHhrZ2s3QWZreFFjSTQKTVJzOG9DVUNnWUVBOVVpODc3d0Z1SUZ5OTJ0OUZTVVd2bmhrVk85QWFCZ0lWOGtkQ29ZaDFTQmlmYlpPdHhOUAo0OVQ2ZW5XRnFLVy9zdG9CUFJHTUQ0WlpYc25PQ3ZlMFVtVHBMNkxmMEROWGNNcVozQytMbE9sd3ZTNTlNUGNmCmFKNzErcEg1QjBlTzNkbWFaNG1TTXBIQXZCSnNRUkxFSXRCK0RNZGF5TUwrQjNJL0hUY2tiOFVDZ1lFQTJkTEgKNzRnWUJIbXN5MGRtVktUTEpWMlU3ZlBXaVZtNWh1WG0rUGhROURsUVlidUo4MnRyNFZSVS9iVHpyNXd4bzA1WQpLN080SER3MnNFTGFJVjk5ZWwvS1hiUTNDNVd1dndXOHZMNEs3UXgrOE1kclQ0aEl5bFlvZU0vTk5pbWtyWTNzCkVhaUhuTWtySFBRS2xjaW1jOHB2Y0RIdWlQRG1vZ0swTEhpdGpDVUNnWUFSL3F3ZHltV0JDNzRyZUs5TWhkUU4KVlRmSEkyWk9QTFVmKzVrdDFIbFc4WEZJVjcrZW5zUVZxdUpWYVpuTXJaeEt1c09zZjBVUFBvUC8rRDR0Zjg2eQozTVJld2t3NU1nc1FNMHptWW5hVERpMC9NOUhyYmJYWUx4Rk11TGpVVitPYlV3T0k1UWJjdnVTczU0MFptUTdhCm53RWdYdC9DS3N3SUw5R0JpeklaSVFLQmdIZktyZDRUa0hIVm9Ldml4bXBDZnQ0N3l3M2FEZUJYa2VxWVFTQW4KSUE1UC90N2d6b3NxUnBnVFV2SjhNNUFlYkVZTmJmd0t5SFB1d1h6S0owQTNUY0NoTVorNjNwTG1iTVh0RjlFTgpDdUUzQUJEVyt6TXdGaWdBbmgxaTJzNnd0RG9tVk8rWktZdVdMcm1ybEs2dlBLdHRaei9pbGZhRjFiQy9uK3JkCkswUnBBb0dBQ3haUnQzTjhldWdNMUo2am9kaDlkRmRlN0hJY2dybmRZMEFSdGF0U0NacjljWkt1WnZaY0g2SnIKcTNtYVhlOU5Cd21ydUtpU0Rpa3VPNGE3aWpnR1huOUhCalU4SnBmaW5lRE81RkRFTmxVUU55VWxGd2hqYU45RgpreVpEQ1ArcnpYWk9mWk9yVVJoeGh5YlY3dW9MZitteVJvRnU1QmRWMkVDY2NQS2plTms9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: liguanghui.pro
  namespace: default
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.liguanghui.pro
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp
            port:
              name: http
  tls:
  - hosts:
    - myapp.liguanghui.pro
    secretName: liguanghui.pro
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: myapp
    release: canary
  ports:
  - port: 80
    name: http
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
    matchExpressions:
    - key: release
      operator: In
      values:
      - canary
  template:
    metadata:
      labels:
        app: myapp
        release: canary
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: default
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - tomcat
    matchLabels:
      release: stable
  template:
    metadata:
      labels:
        app: tomcat
        release: stable
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.5.32-jre8-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     port: http
        #     path: /
        #   failureThreshold: 3
        #   successThreshold: 1
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   timeoutSeconds: 3
        # readinessProbe:
        #   httpGet:
        #     port: http
        #     path: /
        #   failureThreshold: 2
        #   successThreshold: 1
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: tomcat
    release: stable
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  sessionAffinity: ClientIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomat
  namespace: default
spec:
  rules:
  - host: tomcat.liguanghui.pro
    http:
      paths:
      - backend:
          service:
            name: tomcat
            port:
              name: http
        pathType: Prefix
        path: /